### ISSUE TITLE
Allow configuring multiple routes that point to different endpoints

### ISSUE THREAD

**Issue by leonardocustodio** [mll-lab/laravel-graphiql#8]
It seems that using this package we are not able to load different schemas in different endpoints, is that correct?
https://github.com/rebing/graphql-laravel/pull/986/files

**Comment by spawnia** [comment]
In order to make this happen, I think we would essentially need to switch the configuration from the current format into one that returns configurations for multiple routes.

```diff
-return ['route' => ['uri' => '/graphiql', ...], 'endpoint' => '/graphql', ...];
+return [
+    ['route' => ['uri' => '/graphiql/admin', ...]], 'endpoint' => '/graphql/admin', ...],
+    ['route' => [['uri' => '/graphiql/app', ...], 'endpoint' => '/graphql/app', ...],
```

Then, the routes configuration file would need to iterate over those multiple routes and pass their config to the controller, which in turn passes the configuration values to the view.

I am not looking to implement this change myself. but am open to pull requests.

**Comment by v16Studios** [comment]
I adapted our fork to support multiple schemas dynamically in the routes.php, this works for us 😄 :

```
/**
 * Get the schema from the request and append to the configured endpoints.
 */
if ($schema = Str::afterLast(trim(Request::capture()->getPathInfo(), '/'), '/')) {
    $schema = '/' . $schema;
    if ($config->get('graphiql.route.uri') != $schema) {
        $config->set('graphiql.route.uri', $config->get('graphiql.route.uri') . $schema);
        $config->set('graphiql.endpoint', $config->get('graphiql.endpoint') . $schema);
    }
}
```
